openaction/action/urls.py
try:
    from django.conf.urls import patterns, url
except ImportError as e:
    # Using Django < 1.4
    from django.conf.urls.defaults import patterns, url

import action.views as action_views
import action_request.views as action_request_views

urlpatterns = patterns('',
    # Single action view
    url(r'^(?P<pk>\d+)/$', action_views.ActionDetailView.as_view(), 
        name='action-detail'
    ),
    url(r'^create/$', action_views.ActionCreateView.as_view(), 
        name='action-create'
    ),
    url(r'^(?P<pk>\d+)/edit/$', action_views.ActionUpdateView.as_view(),
        name='action-update'
    ),
    url(r'^(?P<pk>\d+)/vote/add/$', action_views.ActionVoteView.as_view(), 
        name='action-vote-add'
    ),
    url(r'^(?P<pk>\d+)/edit/politicians/$', action_views.EditablePoliticianView.as_view(), 
        name='edit-politician'
    ),
    url(r'^(?P<pk>\d+)/edit/(?P<attr>\w+)/$', action_views.EditableParameterView.as_view(), 
        name='edit-parameter'
    ),

    # Action related view (list of actions, comments for action, ...)
    url(r'^comment/(?P<pk>\d+)/vote/add/$', action_views.CommentVoteView.as_view(), 
        name='comment-vote-add'
    ),
    url(r'^(?P<pk>\d+)/comment/add/$', action_views.ActionCommentView.as_view(), 
        name='action-comment-add'
    ),

    url(r'^blogpost/(?P<pk>\d+)/$', action_views.BlogpostDetailView.as_view(),
        name='blogpost-comment'
    ),
    url(r'^blogpost/(?P<pk>\d+)/comment/add/$', action_views.BlogpostCommentView.as_view(),
        name='blogpost-comment-add'
    ),
    url(r'^(?P<pk>\d+)/blogpost/add/$', action_views.ActionBlogpostView.as_view(), 
        name='action-blogpost-add'
    ),
    url(r'^comment/(?P<pk>\d+)/vote/add/$', action_views.CommentVoteView.as_view(), 
        name='comment-vote'
    ),
    #follow/unfollow action
    url(r'^(?P<pk>\d+)/follow/$', action_views.ActionFollowView.as_view(), 
        name='action-follow'
    ),
    url(r'^(?P<pk>\d+)/unfollow/$', action_views.ActionUnfollowView.as_view(), 
        name='action-unfollow'
    ),
    #request to a user to moderate action
    url(r'^(?P<pk>\d+)/moderator/add/$', action_request_views.ActionModerationRequestView.as_view(), 
        name='action-moderation-request'
    ),
    #private message between same Action referrers
    url(r'^(?P<pk>\d+)/message/send/$', action_request_views.ActionMessageRequestView.as_view(), 
        name='action-message-send'
    ),
    #remove moderator
    url(r'^(?P<pk>\d+)/moderator/remove/$', action_views.ActionModerationRemoveView.as_view(), 
        name='action-moderation-remove'
    ),
    #request to change action status to the staff
    url(r'^(?P<pk>\d+)/status/change/$', action_request_views.ActionSetStatusRequestView.as_view(), 
        name='action-status-change-request'
    ),

    url(r'^filter/$', action_views.FilteredActionListView.as_view(),
        name='actions-filter'
    ),

    #categories navigation
    url(r'^argument/(?P<pk>\d+)/$', action_views.ActionByCategoryListView.as_view(),
        name='category-action-list'
    ),

    #geonames navigation
    url(r'^location/(?P<pk>\d+)/$', action_views.ActionByGeonameListView.as_view(),
        name='geoname-action-list'
    ),

)

openaction/action/forms.py
# -*- coding: utf-8 -*-

from django import forms
import askbot.forms as askbot_forms
from action.models import Action, Geoname, ActionCategory, Politician, Media
from askbot.models import User
from django.core import exceptions
from external_resource.models import ExternalResource

from ajax_select import make_ajax_field
from ajax_select import get_lookup

MAP_FIELD_NAME_TO_CHANNEL = {
    'geoname_set' : 'geonamechannel', 
    'politician_set' : 'politicianchannel',
    'media_set' : 'TODO',
}

CITYREP_CHANNEL_NAME = 'cityrepchannel'

INSTITUTIONS = {
    'comune' : ['consiglio','giunta',],
    'provincia' : ['consiglio','giunta',],
    'regione' : ['consiglio','giunta',],
    'senato' : ['representatives',],
    'europarl' : ['representatives',],
    'camera' : ['representatives',],
}

class ActionForm(askbot_forms.AskForm):
    # TOASK: Ajaxification of fields autocomplete?

    in_nomine = forms.ChoiceField(required=True,
        choices=() #will be set in __init__
    )

    threshold = forms.CharField()

    geoname_set = make_ajax_field(Action, 
        label = "Territori",
        model_fieldname='geoname_set',
        channel='geonamechannel', 
        help_text="Search for place by name or by city",
        required=False,
    )
    category_set = forms.ModelMultipleChoiceField(
        queryset=ActionCategory.objects, label=u"Ambiti",
        required=False,
        help_text=u"La scelta degli ambiti può aiutarti a definire meglio i prossimi passi"
    )
    politician_set = forms.MultipleChoiceField(
        label="Politici",
        required=False
    )
    media_set = forms.ModelMultipleChoiceField(
        queryset=Media.objects, label="Media",
        required=False
    ) 

    def __init__(self, request, *args, **kw):
        if kw.get('action'):
            self.action = kw.pop('action')
        user = request.user
        choices = [("user-%s" % user.pk, user),]
        orgs = user.represented_orgs
        for org in orgs:
            choices.append(
                ("org-%s" % org.pk, org)
            )
        super(ActionForm, self).__init__(*args, **kw)
        self.fields['in_nomine'].choices = choices
        if not orgs:
            self.hide_field('in_nomine')

    def _clean_geoname_set(self, cleaned_data):
        """Return a representation of Geoname objects based on 
        the data contained into an external API"""
        #This is _clean method because it has to be called BEFORE _clean_politician_set

        geoname_ids = cleaned_data.get('geoname_set')

        if geoname_ids:
            field_name = 'geoname_set'
            lookup = get_lookup(MAP_FIELD_NAME_TO_CHANNEL[field_name])
            values = lookup.get_objects(geoname_ids)

            if len(values) != len(geoname_ids):
                for value in values:
                    if value in geoname_ids:
                        values.remove(value)
                #raise exceptions.InvalidGeonameListError(values)
                raise exceptions.ValidationError(u"Non tutti i luoghi sono stati recuperati. Sono rimasti fuori i luoghi con id: %s" % values)
            
        else:
            values = []
        
        return values
        
    def _clean_politician_set(self, cleaned_data, geoname_ids):
        """Return a representation of Politician objects based on 
        the data contained into an external API

        Check that the Total threshold come with the form is equal
        to the sum of politicians threshold deltas  """

        field_name = 'politician_set'
        charge_ids = [int(elem) for elem in cleaned_data[field_name].strip('|').split('|')]
        charge_ids_copy = list(charge_ids)

        if charge_ids:

            politician_ids = []

            for cityrep_id in geoname_ids:
                if not len(charge_ids_copy):
                    break
                found_ids, pol_ids = self.get_politicians_from_cityrep(
                    charge_ids_copy,
                    cityrep_id
                )
                for pol_id in pol_ids:
                    politician_ids.append(pol_id)
                #print("\ncityrep_id: %s\ncharge_ids_copy: %s\nfound_ids: %s\n" % (cityrep_id, charge_ids_copy, found_ids))
                for charge_id in found_ids:
                    charge_ids_copy.remove(charge_id)
                
            if len(charge_ids_copy):
                raise exceptions.ValidationError(u"Non tutti i politici sono stati recuperati. Sono rimasti fuori i politici con id: %s" % charge_ids_copy)

            lookup = get_lookup(MAP_FIELD_NAME_TO_CHANNEL[field_name])
            values = lookup.get_objects(politician_ids)

        else:
            values = []

        return values

    def get_politicians_from_cityrep(self, charge_ids, cityrep_id):
        """ Return a list of politicians from a list of city
        representatives """

        lookup = get_lookup(CITYREP_CHANNEL_NAME)
        politician_charges = []
        politician_ids = []

        cityrep_data = lookup.get_objects([cityrep_id])[0]['city_representatives']

        for institution, institution_kinds in INSTITUTIONS.items():

            for inst_kind in institution_kinds:
                cityreps_of_kind = cityrep_data[institution][inst_kind]

                for politician in cityreps_of_kind:
                    if politician['charge_id'] in charge_ids:
                        politician_charges.append(politician['charge_id'])
                        politician_ids.append(politician['politician_id'])

        return politician_charges, politician_ids

    def check_threshold(self, cleaned_data):
        """ Check that the threshold deltas sum is equal to the given total
        threshold. """

        computed_threshold = 0
        politician_data = cleaned_data['politician_set']
        total_threshold = int(cleaned_data['threshold'])

        for datum in politician_data:

            #compute politician threshold
            threshold_delta = self.compute_threshold_delta(datum)
            computed_threshold = computed_threshold + threshold_delta
        print "threshold : %s" % computed_threshold
        if computed_threshold != total_threshold:
            raise exceptions.ValidationError("La soglia indicata non corrisponde a quella ricavata dai politici scelti")

    def compute_threshold_delta(self, politician_datum):
        return 1

    def clean(self):
        """ overriding form clean """
        cleaned_data = super(ActionForm, self).clean()

        cleaned_data['politician_set'] = self.data.get('politician_set',[])
        if self._errors.get('politician_set'):
            del self._errors['politician_set']

        geoname_ids = cleaned_data.get('geoname_set')
        if geoname_ids:
            cleaned_data['geoname_set'] = self._clean_geoname_set(cleaned_data)
        else:
            external_resource_ids = self.action.geonames.values_list('external_resource', flat=True)
            geoname_ids = [external_resource.ext_res_id for external_resource in ExternalResource.objects.filter(pk__in=external_resource_ids)]

        if cleaned_data['politician_set']:
            cleaned_data['politician_set'] = self._clean_politician_set(
                cleaned_data,
                geoname_ids
            )
        self.check_threshold(cleaned_data)
        # set defaults
        for field_name in ('category_set', 'media_set'):
            if not cleaned_data.get(field_name):
                cleaned_data[field_name] = []
        return cleaned_data


#class EditActionForm(askbot_forms.EditQuestionForm):
#    # TOASK: Ajaxification of fields autocomplete?
#
#    threshold = forms.CharField()
#
#    geoname_set = make_ajax_field(Action, 
#        label = "Territori",
#        model_fieldname='geoname_set',
#        channel='geonamechannel', 
#        help_text="Search for place by name or by city",
#        required=False,
#    )
#    category_set = forms.ModelMultipleChoiceField(
#        queryset=ActionCategory.objects, label=u"Ambiti",
#        required=False,
#        help_text=u"La scelta degli ambiti può aiutarti a definire meglio i prossimi passi"
#    )
#    politician_set = forms.MultipleChoiceField(
#        label="Politici",
#        required=False
#    )
#    media_set = forms.ModelMultipleChoiceField(
#        queryset=Media.objects, label="Media",
#        required=False
#    ) 

#----------------------------------------------------------------------------------

class SingleTextareaForm(forms.Form):
    text = forms.CharField(widget=forms.Textarea)

class ActionCommentForm(SingleTextareaForm):
    pass

class BlogpostCommentForm(SingleTextareaForm):
    pass

class ActionAddBlogpostForm(forms.Form):

    title = forms.CharField()
    text = forms.CharField(widget=forms.Textarea)

#--------------------------------------------------------------------------------

class ModeratorRemoveForm(forms.Form):

    moderator = forms.ModelChoiceField(required=True,
        queryset=User.objects.none()
    )

    #text = forms.CharField(required=False)

    def __init__(self, *args, **kwargs):
        action = kwargs.pop('action')
 
        #WAS: followers = action.thread.followed_by.all()
        moderators = action.moderator_set.all()

        super(ModeratorRemoveForm, self).__init__(*args, **kwargs)
        self.fields['moderator'].queryset = moderators

openaction/action/templates/action/action_form.html
{% csrf_token %}

<fieldset class="action-create-step" id="step1">
    {% if form.non_field_errors %}
        <p class="text-error">{{ form.non_field_errors }}</p>
    {% endif %}

    <h2><label for="id_{{ form.title.html_name }}">Per cosa bisogna agire?</label></h2>
    {{ form.title.errors }}
    <input type="text" name="{{ form.title.html_name }}" autocomplete="off" placeholder="Inserisci un titolo..." id="id_{{ form.title.html_name }}" value="{{ form.title.value }}">
    <p class="help"><a href="#" tabindex="-1">Come scrivere un titolo efficace</a></p>

    <label for="id_{{ form.text.html_name }}">Descrivi la questione, perché è importante e cosa vuoi che venga fatto</label>
    {{ form.text.errors }}
    <textarea name="{{ form.text.html_name }}" id="id_{{ form.text.html_name }}" cols="30" rows="10" placeholder="Inserisci un testo...">{{ form.text.value }}</textarea>
    <p class="help"><a href="#" tabindex="-1">Come scrivere un testo efficace</a></p>
</fieldset>

<hr>

<fieldset class="action-create-step" id="step2">
    <h2><label for="{{ form.category_set.html_name }}">Che ambiti riguarda</label></h2>
    {{ form.category_set.errors }}
    {{ form.category_set }}

    <h2><label for="{{ form.tags.html_name }}">Specifica gli argomenti <small>(importante)</small></label></h2>
    {{ form.tags.errors }}
    <p>La scelta degli argomenti può aiutarti a definire meglio i prossimi passi</p>
    {{ form.tags }}
</fieldset>

<hr>

<fieldset class="action-create-step" id="step3">
    <h2><label for="{{ form.geoname_set.html_name }}">Scegli il territorio interessato</label></h2>
    {{ form.geoname_set.errors }}
    <div class="controls">
        {{ form.geoname_set }}
        <label class="btn disabled" for="ambito-nazionale"><input type="checkbox" id="ambito-nazionale" style="margin:0;" name="ambito-nazionale"> Ambito nazionale</label>
        <p class="help"><a href="#" tabindex="-1">Come scegliere un territorio</a></p>
    </div>
</fieldset>

<hr>

<fieldset class="action-create-step" id="step4">
    <h2><label for="id_{{ form.politician_set.html_name }}">Scegli i decisori</label></h2>
    <p>Questa opzione è collegata alla scelta degli argomenti e del territorio.</p>
    {{ form.politician_set.errors }}
    <input type="hidden" id="id_{{ form.politician_set.html_name }}" name="{{ form.politician_set.html_name }}" value="|{% for politician_id in form.politician_set.value %}{{ politician_id }}|{% endfor %}" />
    <div id="politician_accordion" class="accordion">

    </div>
    <p class="help"><a href="#" tabindex="-1">Come scegliere i decisori</a></p>

    {#    {{ form.as_p }}#}
</fieldset>
<fieldset>
    {{ form.threshold }}
    {{ form.in_nomine }}
    <p class="action-form"><input type="submit" class="btn btn-info btn-large" value="{{ save_text|default_if_none:'Salva' }}"></p>
</fieldset>

openaction/action/templates/action/action_list.html
{% extends 'base.html' %}
{% load action_tags %}

{% block head_scripts %}
  {{ block.super }}
  <script type="text/javascript" src="{{ STATIC_URL }}js/bootstrap-tab.js"></script>
{% endblock head_scripts %}

{% block content %}

  <article class="action-list">
    {% if filter_object %}
    <h1>{{ filter_object }}</h1>
    {% else %}
    <h3>{% if request.GET.q %}{{ actions_count }} azioni su "{{ request.GET.q }}"{% else %}Tutte le Azioni{% endif %}</h3>
    {% endif %}

    <div id="action-slideshow"></div>

    {% html_action_list object_list %}

  </article>

{% endblock content %}

{% block sidebar %}
  <h2>{{ actions_count }} azioni attive <br>
  {{ activists_count }} attivisti coinvolti</h2>

  <iframe width="100%" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.it/maps?f=q&amp;source=s_q&amp;hl=it&amp;geocode=&amp;q=roma&amp;aq=&amp;sll=40.894451,12.086871&amp;sspn=5.089885,9.547119&amp;t=m&amp;ie=UTF8&amp;hq=&amp;hnear=Roma,+Lazio&amp;z=11&amp;iwloc=&amp;output=embed"></iframe>
  <p><strong>Comune di Roma</strong><br>Provincia di Roma, Regione Lazio</p>

  <hr>

  <h4>Ultime dalle Action su {% if filter_object %}{{ filter_object }}{% else %}{{ request.GET.q }}{% endif %}</h4>
  {% for news in latest_news %}
  <div class="related-news">
    <h3><a href="{{ news.action.get_absolute_url }}">{{ news.action.bare_title }}</a></h3>
    <h4><a href="{% url blogpost-comment pk=news.pk %}">{{ news.title }}</a></h4>
    {{ news.added_at }} - <a href="#">Leggi tutto</a>
  </div>
  {% endfor %}
  <hr>

  <h4>Organizzazioni più attive</h4>
  {% html_voter_list organizations %}
  <a href="#">Tutte le organizzazioni</a>

  <hr>

  <h4>Utenti più attivi</h4>
  {% html_voter_list users %}
  <a href="#">Tutti i sostenitori</a>

{% endblock %}

openaction/action/templates/action/action_share_modal.html
<div class="modal hide fade" id="share-modal" tabindex="-1" role="dialog" aria-labelledby="Share" aria-hidden="true">
    <div class="modal-body">

        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>

        <h4>{{ request.user.username }}, grazie per aver aderito. <br>Aiutaci ad incoraggiare anche gli altri a farlo.</h4>
        <p class="lead">
            Scrivici perchè hai aderito:
        </p>

        <form action="{% url action-comment-add action.pk %}" method="post">
          {% csrf_token %}
            <fieldset>
                <textarea name="text" id="id_text" class="span5"></textarea><br>
                <input class="btn" type="submit" name="submit" value="Pubblica sull'azione">
            </fieldset>
        </form>

    </div>
</div>

openaction/action/templates/action/create.html
{% extends 'base.html' %}
{% load action_tags %}

{% block head_scripts %}
    {{ block.super }}
    <script type="text/javascript" src="{{ STATIC_URL }}js/bootstrap-transition.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/bootstrap-collapse.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/bootstrap-affix.js"></script>
{% endblock %}

{% block footer_js_includes %}
    <script type="text/javascript">
        var MIN_THRESHOLD = 1;
        var geoname_form_id = "#id_{{ form.geoname_set.html_name }}";
        var geoname_form_deck_id = "#id_{{ form.geoname_set.html_name }}_on_deck";
        var politicians_form_id = "#id_{{ form.politician_set.html_name }}";
        var politicians_table_id = "#politician_accordion";
        var spinner_loader = $('<img src="https://raw.github.com/crucialfelix/django-ajax-selects/master/ajax_select/static/images/loading-indicator.gif" />').css('margin-left','10px').appendTo($('#step4').find('h2 label')).hide();

        var cached_geoname_pks = [], cached_geonames= {};

        function parsePipedPks( text ) {
            // example : |1|2|3|4|
            var pks = text.split('|').map(function(el){ return el ? parseInt(el,10) : el});
            pks.pop(); pks.shift();
            return pks;
        }

        function encodePks( list ) {
            var text = '|';
            list.forEach(function(item){
                text += item + '|';
            });
            return text;
        }

        function updatePoliticiansTable() {

            var table = $(politicians_table_id), politician;

            // remember old selections
            var selected = parsePipedPks($(politicians_form_id).val());
            $('input:checked', table).each(function() { selected.push(parseInt($(this).val(),10)); });

            // clean all
            table.children().fadeOut('slow').remove();

            // init context
            var added = [], accordion_groups = {}, is_first = true;

            reset_threshold();

            for(var i = 0; i < cached_geoname_pks.length; i++) {
                var group_list = cached_geonames[ cached_geoname_pks[i] ]['value']['city_representatives'];

                for (var group in group_list ) { if ( !group_list.hasOwnProperty(group) || group == 'location' ) continue;
                    var body;
                    var to_add = [];

                    if ( group == 'comune' || group == 'regione' || group == 'provincia' ) {
                        for (politician in group_list[group]['consiglio'])  { to_add.push( group_list[group]['consiglio'][politician] ); }
                        for (politician in group_list[group]['giunta'])     { to_add.push( group_list[group]['giunta'][politician] ); }
                    }
                    else if ( group == 'camera' || group == 'senato' || group == 'europarl') {
                        to_add = group_list[group]['representatives'];
                    }

                    if ( !accordion_groups.hasOwnProperty(group) ) {
                        var header = $('<div class="accordion-heading"></div>').append(
                                '<a class="accordion-toggle" data-toggle="collapse" data-parent="'+politicians_table_id+'" href="#accordion_'+ group +'">'+ group + ' (<span>'+ to_add.length +'</span>)</a>'
                        );
                        //var container = $('<div class="accordion-body collapse'+(is_first ? ' in' : '')+'" id="accordion_'+ group +'"></div>').append(
                        var container = $('<div class="accordion-body collapse" id="accordion_'+ group +'"></div>').append(
                                body = $('<div class="accordion-inner"></div>').css({ 'max-height': '200px', 'overflow': 'auto' })
                        );
                        //is_first && ( is_first = false );
                        //body = $('<div class="accordion-inner"></div>').css({ 'max-height': '200px', 'overflow': 'auto' }).appendTo(container);#}
                        accordion_groups[group] = $('<div class="accordion-group"></div>').append(header, container);
                    }
                    else {
                        var length_el = $('.accordion-heading a span', accordion_groups[group]);
                        length_el.text( parseInt(length_el.text()) + to_add.length );
                        body = $('.accordion-inner', accordion_groups[group]);
                    }

                    for (politician in to_add) {
                        // check if already added from other location
                        if (body.find('input[value='+to_add[politician]['charge_id']+']').length == 0) {
                            var is_selected = selected.indexOf(to_add[politician]['charge_id']) != -1,
                                check_box_el = $('<label class="checkbox">'+to_add[politician]['first_name']+' '+to_add[politician]['last_name']+'</label>')
                                .prepend( $('<input type="checkbox" name="politician_set_pks" value="'+to_add[politician]['charge_id']+'" />').attr('checked', is_selected) );
                            body.append(check_box_el);
                            is_selected && add_threshold(1);
                        }
                    }
                    // update count
                    body.parent().parent().find('.accordion-toggle span').text(body.children().length);

                }
            }

            for (var group_name in accordion_groups) {
                if ($(accordion_groups[group_name]).find('.accordion-toggle span').text() == '0') { continue;}
                table.append( accordion_groups[group_name] );
            }

            table.find('.accordion-body').first().addClass('in');
            table.collapse();
            spinner_loader.hide();
            $(politicians_table_id).css('height', 'auto');
        }

    var set_threshold = function(qnt) {
        $('#current-threshold').text(qnt);
    };
    var add_threshold = function(qnt) {
        set_threshold(parseInt($('#current-threshold').text(),10) + qnt)
    };
    var reset_threshold = function() { set_threshold(0); };

    $(document).ready(function(){

        // fix for collapse with dynamic content: https://github.com/twitter/bootstrap/issues/2274
        $(politicians_table_id).on('show hide', function() {
            $(this).css('height', 'auto');
        });

        // selection of politician populate politician_set fields
        $(politicians_table_id).on('click', 'input[type=checkbox]', function() {
            var value_list = $(politicians_form_id).val();
            var new_value = $(this).val();
            if ($(this).is(':checked')) {
                if (value_list.length == 0) value_list = '|';
                $(politicians_form_id).val(value_list + new_value +'|');
                add_threshold(1);
            }
            else {
                value_list = value_list.replace('|' + new_value +'|', '|');
                $(politicians_form_id).val( value_list == '|' ? '' : value_list );
                add_threshold(-1);
            }
        });

        // event triggered in autocompleteselectmultiple_geonamechannel
        $(geoname_form_id).on('geoname_loaded', function( e, item ) {
            cached_geonames[item.pk] = item;
        });

        $(geoname_form_deck_id).on('added',function() {
            spinner_loader.show();
            var pks = parsePipedPks( $(geoname_form_id).val() );
            var added_id = pks.filter(function(pk){ return cached_geoname_pks.indexOf(pk) == -1 ; }).pop();
            if (added_id) {
                cached_geoname_pks.push(added_id);
                $.getJSON('/external/cityreps/'+ added_id, function(data) {
                    cached_geonames[ added_id ]['value']['city_representatives'] = data['city_representatives'];
                    updatePoliticiansTable();
                });
            }
        });
        $(geoname_form_deck_id).on('killed',function() {
            spinner_loader.show();
            var pks = parsePipedPks( $(geoname_form_id).val() );
            var removed_id = cached_geoname_pks.filter(function(pk){ return pks.indexOf(pk) == -1 ; }).pop();
            if (removed_id) {
                console.log('remove',removed_id);
                cached_geoname_pks = pks;
                updatePoliticiansTable();
            }
        });

        // read selected to convert from politician_id to charge_id
        var politician_pks = parsePipedPks( $(politicians_form_id).val() );

        // read initial data
        var charges_pks = [];
        parsePipedPks( $(geoname_form_id).val() ).forEach(function(geoname_pk, index, geonames){
            if (index==0) { spinner_loader.show(); }
            $.getJSON('/external/locations/'+geoname_pk, function(item){
                cached_geonames[geoname_pk] = {'value': item};
                cached_geoname_pks.push(geoname_pk);
                $.getJSON('/external/cityreps/'+geoname_pk, function(data){
                    cached_geonames[ geoname_pk ]['value']['city_representatives'] = data['city_representatives'];

                    var politician, group_list = data['city_representatives'];
                    for(var group in group_list) {
                        var to_add = [];
                        if ( group == 'comune' || group == 'regione' || group == 'provincia' ) {
                            for (politician in group_list[group]['consiglio'])  { to_add.push( group_list[group]['consiglio'][politician] ); }
                            for (politician in group_list[group]['giunta'])     { to_add.push( group_list[group]['giunta'][politician] ); }
                        }
                        else if ( group == 'camera' || group == 'senato' || group == 'europarl') {
                            to_add = group_list[group]['representatives'];
                        }
                        to_add.forEach(function(politician){
                            if ( politician_pks.indexOf(politician['politician_id']) !== -1 ) {
                                charges_pks.push(politician['charge_id']);
                            }
                        })
                    }

                    // if is last
                    if (index == geonames.length -1) {
                        // convert politician_id to charge_id
                        //console.log('convert',$(politicians_form_id).val());
                        $(politicians_form_id).val( encodePks(charges_pks) );
                        //console.log('converted',$(politicians_form_id).val() );

                        updatePoliticiansTable();
                    }
                });
            });
        });

        $('.action-create-form').on('submit', function(){
            var threshold = parseInt($('#current-threshold').text(), 10);
            if (threshold <= MIN_THRESHOLD) { return false; }
            $('#id_threshold').val(threshold);
        });

    });

    </script>
{% endblock %}



{% block content %}
  <h1>Crea un'Azione</h1>
  <p>Questo è un testo introduttivo che presenta brevemente cosa fare e incoraggia l'utente a completare il form.</p>

    <form action="{% url action-create %}" method="post" class="action-create-form">
      {% include "action/action_form.html" with save_text='Salva come bozza' %}
    </form>

{% endblock content %}

{% block sidebar %}

  <div class="highlights hidden-phone">
  <strong>Stai creando un'azione</strong>
  <ul>
    <li>1) <a href="#step1">Scrivi per cosa bisogna agire</a></li>
    <li>2) <a href="#step2">Quali argomenti riguarda</a></li>
    <li>3) <a href="#step3">Il territorio interessato dall'Azione</a></li>
    <li>4) <a href="#step4">Scegli i decisori da coinvolgere</a></li>
  </ul>
  </div>

  <div id="action-create-helper" class="well affix-bottom" data-spy="affix" data-offset-top="100">
    <p>{% html_render_resource request.user %}, stai facendo un ottimo lavoro.</p>
    <p>
      Considera che nella scelta dei decisori
      maggiore è la quantità maggiore sarà
      l'impegno per rendere pubblica e
      attiva l'azione.
    </p>
    <p>
      In questo momento la tua azione può<br>
      attivarsi con l'adesione di:
    </p>
    <p class="lead bigger"><span id="current-threshold">0</span> persone</p>

    <a href="#">Come funziona la scelta dei decisori.</a>

  </div>

{% endblock %}

openaction/action/templates/action/update.html
{% extends 'action/create.html' %}

{% block content %}
    <h1>Modifica Azione</h1>

    <form action="{% url action-update pk=form.action.pk %}" method="post" class="action-create-form">
        {% include "action/action_form.html" with save_text='Modifica' %}
    </form>

{% endblock content %}